version: '3.4'

services:
  ecommercesearchservice:
    image: ecommercesearchservice
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200
volumes:
  es_data:
    driver: local
