version: '3.4'

services:
  ecommercesearchservice:
    image: ecommercesearchservice
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 8080:8080
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: trending
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  es_data:
    driver: local
  db-data:
    driver: local
